//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthBuddy.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllSaHospital
    {
        public int Id { get; set; }
        public Nullable<int> DHS_ID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string SUBURB { get; set; }
        public Nullable<int> POSTCODE { get; set; }
        public string SUBTYPE { get; set; }
        public string LABEL { get; set; }
        public string DEPT { get; set; }
        public string MET { get; set; }
        public string XCORD { get; set; }
        public string YCORD { get; set; }
    }
}
