//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthBuddy.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ED001_HospitalStatus
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string HospitalCode { get; set; }
        public Nullable<long> ExpectedArrivals { get; set; }
        public Nullable<long> EdWaiting { get; set; }
        public Nullable<long> EdCommenced { get; set; }
        public Nullable<long> Capacity { get; set; }
        public string EdCurrentStatus { get; set; }
        public Nullable<decimal> AvgWaitTimeMinsExclHigh { get; set; }
    }
}
