//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthBuddy.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emergencydept4hourlengthofstaymetadata
    {
        public int ID { get; set; }
        public string Quarter { get; set; }
        public string HospitalID { get; set; }
        public string HospitalName { get; set; }
        public Nullable<decimal> LessThan4HrsPct { get; set; }
        public string Year { get; set; }
        public Nullable<int> MyHospitalsId { get; set; }
        public string HospitalCode { get; set; }
    }
}
