//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthBuddy.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class myhospitals_contact_data
    {
        public int Id { get; set; }
        public string Hospital_name { get; set; }
        public string Phone_number { get; set; }
        public string Street_address { get; set; }
        public string Suburb { get; set; }
        public string Postcode { get; set; }
        public string State { get; set; }
        public string Website { get; set; }
        public string Description { get; set; }
        public string Sector { get; set; }
        public string Beds { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string HospitalCode { get; set; }
        public Nullable<bool> Child { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> Emergency { get; set; }
    }
}
