//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthBuddy.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaCommunityServiceDirectory
    {
        public int Id { get; set; }
        public string Organization_Name { get; set; }
        public string Street_Address { get; set; }
        public string Supplemental_Address_1 { get; set; }
        public string Supplemental_Address_2 { get; set; }
        public string City { get; set; }
        public Nullable<int> Postal_Code { get; set; }
        public string StreetAddress_State { get; set; }
        public string PostalAddress_Street_Address { get; set; }
        public string PostalAddress_Supplemental_Address_1 { get; set; }
        public string PostalAddress_Supplemental_Address_2 { get; set; }
        public string PostalAddress_City { get; set; }
        public Nullable<int> PostalAddress_Postal_Code { get; set; }
        public string PostalAddress_State { get; set; }
        public string Phone__1 { get; set; }
        public string Phone__2 { get; set; }
        public string Mobile__1 { get; set; }
        public string Mobile__2 { get; set; }
        public string Mobile__2_Comment { get; set; }
        public string Fax__1 { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string Parent_Body { get; set; }
        public string Contact { get; set; }
        public string Hours { get; set; }
        public string Meetings { get; set; }
        public string Eligibility { get; set; }
        public string Comment { get; set; }
        public string Services { get; set; }
        public string ABN { get; set; }
        public Nullable<System.DateTime> Last_updated { get; set; }
        public Nullable<long> Internal_Contact_ID { get; set; }
    }
}
